owner: videoscape
repo: status
user-agent: VSN-Status-Agent
sites:
  - name: Plex
    url: $PLEX
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Support Site
    url: https://help.vsnet.uk
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Frontend
    url: $FRONTEND
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Backend Control Panel
    url: $BACKENDCP
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: TV Backend
    url: $TVBKEND
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Movie Backend
    url: $MOVIEBKEND
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Requester
    url: https://request.vsnet.uk/login
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    expectedStatusCodes:
      - 200
  - name: Downloader Backend 1
    url: $DLBK1
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Downloader Backend 2
    url: $DLBK2
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Indexer and VPN Service
    url: $INDEXER
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
  - name: Analytics Service
    url: $ANALYTICS
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_SMTP: true
    NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
    NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
    NOTIFICATION_DISCORD: true
    NOTIFICATION_SLACK_WEBHOOK: true
    expectedStatusCodes:
      - 200
    headers:
      - "CF-Access-Client-Id: $CFID"
      - "CF-Access-Client-Secret: $CFSEC"
      - User-Agent' => 'VSN-Status-Agent'
    __dangerous__disable_verify_peer: true
    __dangerous__insecure: true
status-website:
  cname: status.vsnet.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Versus Networks Status
  theme: dark
  NOTIFICATION_EMAIL: true
  NOTIFICATION_EMAIL_SMTP: true
  NOTIFICATION_EMAIL_FROM: 'service@vsnet.uk'
  NOTIFICATION_EMAIL_TO: 'p8ki2ri5@anonr.uk'
  NOTIFICATION_DISCORD: true
  NOTIFICATION_SLACK_WEBHOOK: true
#workflowSchedule:
#  graphs: "*/8 * * * *"
#  responseTime: "*/8 * * * *"
#  staticSite: 0 1 * * *
#  summary: "*/8 * * * *"
#  updateTemplate: 0 0 * * *
#  updates: 0 3 * * *
#  uptime: "*/8 * * * *"
